### ISSUE TITLE
Move InterpretationRemarkSeverity from occurrence-common

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#10]
In relation of Issue #5 
The gbif-api should also define the default "severity" of each interpretation remarks.

The severity of an interpretation remarks can be different depending on the context. Here, we only want to define the default severity.

**Comment by mdoering** [comment]
https://github.com/gbif/gbif-api/commit/f3d2774e40ec491a3e1d3efb3e26bd69b887da3c
