### ISSUE TITLE
Errors when POST to occurrence/download/request

### ISSUE THREAD

**Issue by dshorthouse** [gbif/gbif-api#101]
Sending a POST with this document: https://github.com/bionomia/bionomia/blob/master/bionomia_gbif_request.json to https://api.gbif.org/v1/occurrence/download/request

Produces errors such as:
```
#/predicate: expected: null, found: JSONObject
#/predicate/predicates/2/predicates/1: required key [predicates] not found
#/predicate/predicates/2/predicates/1: extraneous key [predicate] is not permitted
#/predicate/predicates/2/predicates/1/type: not is not a valid enum value
#/predicate/predicates/2/predicates/1: required key [predicates] not found
#/predicate/predicates/2/predicates/1: extraneous key [predicate] is not permitted
#/predicate/predicates/2/predicates/1/type: not is not a valid enum value
#/predicate/predicates/2/predicates/1: required key [key] not found
#/predicate/predicates/2/predicates/1: required key [value] not found
#/predicate/predicates/2/predicates/1: extraneous key [predicate] is not permitted
#/predicate/predicates/2/predicates/1/type: not is not a valid enum value
#/predicate/predicates/2/predicates/1: required key [key] not found
#/predicate/predicates/2/predicates/1: required key [value] not found
etc.
```
...and the download is not produced. Has the expected structure of the request JSON document changed in the last two weeks?

**Comment by ManonGros** [comment]
Possibly relates to: https://github.com/gbif/portal-feedback/issues/4525

**Comment by dshorthouse** [comment]
> Possibly relates to: [gbif/portal-feedback#4525](https://github.com/gbif/portal-feedback/issues/4525)

Could be related, but I think this one's a different root cause. I had hope to execute a refresh for Bionomia, but will have to wait until I get some feedback if the JSON doc I'm posting no longer works in the way it's constructed.

**Comment by MattBlissett** [comment]
Hi David, 

That is the same error, although on `matchCase` rather than `sendNotification`.  If you remove the quotes around the `true` values the request should work.

```json
"matchCase": true
```

(Otherwise, we should fix the API to accept both ways tomorrow.)

**Comment by dshorthouse** [comment]
Aha! Of course! Thanks for taking a look.
