### ISSUE TITLE
API endpoint for the data validator

### ISSUE THREAD

**Issue by rukayaj** [gbif/gbif-api#106]
I was just wondering if there was an endpoint for the darwin core archive validation tool on https://www.gbif.org/tools/data-validator ?

**Comment by MattBlissett** [comment]
Yes, and it's now documented on the new technical documentation site: https://techdocs.gbif.org/en/openapi/v1/validator

(Although only minimally, https://github.com/gbif/pipelines/issues/1028 is an issue for us to complete the documentation.)
