### ISSUE TITLE
`techdocs.gbif.org`: Type mismatch for occurrence api

### ISSUE THREAD

**Issue by mpitblado** [gbif/gbif-api#117]
URI that this issue occurred on: https://techdocs.gbif.org/en/openapi/v1/occurrence#/Occurrences/getOccurrenceByDatasetKeyAndOccurrenceId

I noticed on the technical documentation site that the parameters for `/occurrence/{datasetKey}/{occurrenceId}` are documented as `integer($int64)` but are listed to take UUID keys that are string format. Trying to use the "try it out feature" results in the site producing an error when the user submits the examples supplied for the GET request.

Documentation
![API documentation screenshot showing the GET request form](https://github.com/gbif/gbif-api/assets/116753126/cc40de54-74c8-49f5-b77b-cee20935718b)

Try it out feature after submitting GET request with pre-filled examples
![API documentation screenshot showing the error message that results from submitting the example parameters](https://github.com/gbif/gbif-api/assets/116753126/1cbcf89c-6543-40b0-9a9d-f2902d2ac8ef)

**Comment by marcos-lg** [comment]
Fixed in the code and in dev: https://github.com/gbif/occurrence/commit/391dc3a0bd0a83c14a5def2c76860d9f78412f29. 

Just needs deployment in UAT and production.

**Comment by marcos-lg** [comment]
Deployed
