### ISSUE TITLE
Decide on the future of unused continent related occurrence remarks

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#12]
We currently have 3 occurrence remarks related to continent that are not used (based on Solr facets):
* CONTINENT_COUNTRY_MISMATCH
* CONTINENT_INVALID
* CONTINENT_DERIVED_FROM_COORDINATES

Considering there is no official list of continents, we could consider deprecating `CONTINENT_COUNTRY_MISMATCH` and `CONTINENT_DERIVED_FROM_COORDINATES`.

`CONTINENT_INVALID` could be kept to flag values that can not be matched against the dictionary.

**Comment by MattBlissett** [comment]
These issues are now used for  continent interpretation.
