### ISSUE TITLE
`/species/{usageKey}/identifier` route returns nothing

### ISSUE THREAD

**Issue by AntoineAA** [gbif/gbif-api#136]
Hello,

I would like to get taxon identifiers, such as those displayed at the bottom of this page, for example, in the "taxon identifiers" category: https://www.gbif.org/species/3189863

To do this, I'm using the https://api.gbif.org/v1/species/3189863/identifier route, but there are never any results (tested on several species).

Is this an issue with this API route or am I using the wrong one?

Thanks,

Antoine

**Comment by mdoering** [comment]
if you look at the page resources you can see the data comes from wikidata and is retrieved through some internal GBIF API:
https://www.gbif.org/api/wikidata/species/3189863?locale=en

@MortenHofft can you explain what the call is exactly doing?

**Comment by ManonGros** [comment]
Hi @AntoineAA You can read more about it here: https://discourse.gbif.org/t/given-a-gbif-human-readable-webpage-for-a-species-how-to-find-the-api-call-for-each-item-on-the-page/

You are also welcome to check our latest Data Use Club session about accessing species information from GBIF in general: https://vimeo.com/showcase/9533896/video/949141282

**Comment by AntoineAA** [comment]
Hi,

Thank you for your replies.

If I understand correctly, this route cannot be used by external clients (dedicated to internal use only)?

I have to use the Wikidata API

**Comment by MortenHofft** [comment]
yes. The WikidataAPI is public and it is what we use too. `https://www.gbif.org/api/wikidata/..` can disappear at any moment. You cannot rely on it in any production environment. 
And even if it is just for a script here and now, then you would probably get us blocked if you started hammering it. We are just proxying the request to wikidata's API

**Comment by AntoineAA** [comment]
OK, thank you for all your answers!

I'm going to use the Wikibase SDK to retrieve the data I need (EPPO codes).
