### ISSUE TITLE
Feature request: Added & published params to the Literature API search endpoint

### ISSUE THREAD

**Issue by dshorthouse** [gbif/gbif-api#137]
Use of `added` and `published` as search params for `/literature/search` alongside lt, eq, gt operators would be very helpful for use cases that poll the endpoint for new entries.

**Comment by dnoesgaard** [comment]
Perhaps add `discovered` and `modified` to this as well :)

**Comment by ahakanzn** [comment]
Requested parameters are deployed to prod.

**Comment by dshorthouse** [comment]
This is awesome! Saves me lots of unnecessary processing.

**Comment by dnoesgaard** [comment]
Same! 🕺🏼

**Comment by dshorthouse** [comment]
Tried using a date range, `2024-08-01,2024-08-14` as indicated in the OpenAPI docs on `added` and received an error message, "Value must be a DateTime". Although I have not yet tried a date range in the endpoint directly for these new search params, I assume that it'll throw an error there as well. A date range would be a useful and necessary feature for my particular use-case that polls for new entries since the last time I checked.

**Comment by dnoesgaard** [comment]
Works with direct request, e.g. https://api.gbif.org/v1/literature/search?discovered=2023-01-01,2023-12-31&literatureType=journal&relevance=GBIF_USED&peerReview=true&limit=0&facet=citationtype

**Comment by dshorthouse** [comment]
> Works with direct request, e.g. https://api.gbif.org/v1/literature/search?discovered=2023-01-01,2023-12-31&literatureType=journal&relevance=GBIF_USED&peerReview=true&limit=0&facet=citationtype

Cool! Shoulda done that first. I suppose then it's the OpenAPI UI that might need a tweak.

**Comment by dnoesgaard** [comment]
(btw, I'm waaay behind on adding papers, I'm up to mid-June right now)

**Comment by dshorthouse** [comment]
> (btw, I'm waaay behind on adding papers, I'm up to mid-June right now)

Can't wait for the flood! A couple dozen folk subscribe to weekly, compiled email alerts for new papers that referenced GBIF downloads containing specimen records that they collected/identified. They might be similarly flooded, which is great!

**Comment by dnoesgaard** [comment]
I'm glad to hear someone is using it! 😸

**Comment by dshorthouse** [comment]
Noticed that /v1/literature is presently throwing 500 responses with simple requests like https://api.gbif.org/v1/literature/search?literatureType=JOURNAL. Something wrong in my request?

**Comment by ahakanzn** [comment]
Hi @dshorthouse, it seems like the literature web service experienced outage last night, but everything is should be back to normal now. If you have any further issues, please let us know.
