### ISSUE TITLE
Species Match API Returning 404 for Two-Letter Genus Names When Using genus Parameter

### ISSUE THREAD

**Issue by arhyneRWU** [gbif/gbif-api#150]
1. Fails (404):

Query: `https://api.gbif.org/v1/species/match?name=Aa&strict=false&verbose=true&kingdom=Plantae&genus=Aa`
Response: `404 - Undocumented Error: response status is 404`

2. Unexpected HIGHERRANK Response:

Query: `https://api.gbif.org/v1/species/match?name=Aa%20lehmannii&strict=false&verbose=true&kingdom=Plantae&genus=Aa`
Response: json
```

{
  "usageKey": 2850872,
  "scientificName": "Aa Rchb.f.",
  "canonicalName": "Aa",
  "rank": "GENUS",
  "status": "ACCEPTED",
  "confidence": 99,
  "note": "Similarity: name=100; classification=6; rank=12; status=1; score=119; nextMatch=5",
  "matchType": "HIGHERRANK",
  "kingdom": "Plantae",
  ...
}
```

**Successful Match without genus Parameter:**

Query: `https://api.gbif.org/v1/species/match?name=Aa%20lehmannii&strict=false&verbose=true&kingdom=Plantae`
Response:json
```

{
  "usageKey": 9433259,
  "scientificName": "Aa lehmannii Rchb.f. ex Szlach. & Kolan.",
  "canonicalName": "Aa lehmannii",
  "rank": "SPECIES",
  "status": "ACCEPTED",
  "confidence": 99,
  "matchType": "EXACT",
  ...
}
```

**Passes (EXACT response for longer name):**

Query: `https://api.gbif.org/v1/species/match?name=Aloe&strict=false&verbose=true&kingdom=Plantae&genus=Aloe`
Response: json

```
{
  "usageKey": 2770879,
  "scientificName": "Aloe L.",
  "canonicalName": "Aloe",
  "rank": "GENUS",
  "status": "ACCEPTED",
  "confidence": 95,
  "note": "Similarity: name=100; authorship=0; classification=6; rank=0; status=1; score=107; nextMatch=0",
  "matchType": "EXACT",
  ...
}
```

**Comment by mdoering** [comment]
It was a code bug when name and genus had just 2 letter genera content. Will be deployed in a few days to prod
