### ISSUE TITLE
Introduce Occurrence isoEventDate field(s)

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#2]
The current Occurrence `eventDate` field is a Java `Date` field and it can not always represent the value that was provided. For example, the value "2013-02" is a valid ISO date but can not be stored in a `Date` field without introducing a false precision: "2013-02-01:00:00:00". The issue at this point is that we have no mechanism to return to the user the date at the same level of granularity that was originally provided.

I suggest we introduce fields `isoEventDateStart` and `isoEventDateEnd` to store the rendered ISO date in String. The start and end concept will be used to support date ranges.

**Comment by mdoering** [comment]
Have you thought about creating a custom ISODate type/class instead that we would use for the eventDate field and potentially others? It could serialize into the real ISO format

**Comment by cgendreau** [comment]
I have 2 concerns with a custom ISODate:
 - We would have to deal with ser/de. Deserialization with optional parts is not always straightforward.
 - Most of the time, we would do all of the deserialization into a typed object to serialize it again in String to return it as JSON.

**Comment by mdoering** [comment]
but it would allow us to keep the single dwc term as a java property which is nice. Do you think ser/de really is an issue? we need to parse that anyways from the raw data

**Comment by cgendreau** [comment]
I don't think we can keep a single DwC term since it would be unclear for date ranges what it represents.

The issue I see with ser/de is that it's a lot of computing for, in almost all of the cases, nothing.

**Comment by mdoering** [comment]
can you give an example of an unclear ISO date? I would have thought it is rather straight forward if it is proper ISO. The dirty parsing happens only once when interpreting

**Comment by cgendreau** [comment]
I said it would be unclear because I assumed one date per field, in the sense that we would have eventDate + another field when it's a date range. I just think it makes it more clear with `startEventDate` and `endEventDate` even if they are not DwC Terms. But, we could indeed update the eventDate accordingly. I think it makes it easier for users of the API (including ourselves) to have a range in 2 differents variables.

**Comment by MattBlissett** [comment]
If a Java Date can't represent the data the field needs to store, we shouldn't keep it in the API — that's confusing to users who won't notice they're getting partial/wrong data.

DWC is pretty clear that this is a "date or interval", so I think it's reasonable that someone using the API, but not wanting to handle intervals, has to decide to do something, like discard one end, or calculate the midpoint.

**Comment by cgendreau** [comment]
yes, the current Java Date eventDate should be replaced. This is a breaking change (for the Java user) but I would be in favor of it since currently it is not accurate.

But, there is 2 different things here:
 - The JSON response of the API
 - How it is store in the Java model

This issue was initially to mentioned how this would be stored in the Java model.

As for the JSON serialization, I'm not convinced that returning date ranges in `eventDate` makes the API better. It think it makes it more complicated to use. Maybe it would be more compliant with DwC but I would prioritize usability and simplicity.

Possible return values using the current single "eventDate":
```
"eventDate":"2012-03/2012-04"
"eventDate":"2012-03-01/2012-04-02"
"eventDate":"2012-03-01"
"eventDate":"2012-03"
```

**Comment by mdoering** [comment]
I agree Christian. From a JSON API perspective a possible range given in 2 fields is simpler to use. From a Java perspective I quite like a single date Range instance. Whether custom or based on an existing Range classes like guavas, it is very convenient to use and I think even simpler than 2 properties.

This might be a silly idea, but what if we had a single range class property which serlialized into 2 distinct json fields so both json and java users would benefit?

**Comment by MortenHofft** [comment]
As a consumer I would definitely prefer 2 fields.

**Comment by cgendreau** [comment]
@mdoering the range is optional so would you use the same date in case it is not a date range?

The other question would be a `Range` of which type? We can't use Java 8 the abstract type `TemporalAccessor`, we could potentially upgrade [AtomizedLocalDateTime](https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/date/AtomizedLocalDateTime.java) to implement `Comparable` or we could simply rely on the ISO date `String` lexical order.

**Comment by cgendreau** [comment]
So, the current idea for the occurrence JSON response (after discussion with @mdoering and @MortenHofft + the comment of @MattBlissett) :
 - eventDate would contain the ISO compliant date **including** date ranges and partial dates
 - atomic fields (year, month, day) would be deprecated to avoid confusion in case of date ranges

They are both important breaking changes that requires API users option and idea.
cc @sckott

**Comment by sckott** [comment]
I like the move to only using `eventDate`, and including date range and partial dates in that field. On the client side, in some libraries we just give back parsed JSON data verbatim, so this isn't an issue, but in another client library we do parse dates (`eventDate` specifically, atomic fields [year, month, day] were not used), but this is an easy change to deal with
