### ISSUE TITLE
Regex on AbstractGbifUser doesn't allow dash (-)

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#20]
Emails like `aa@aa.bb-cc.org` are currently rejected but the format is actually valid.

**Comment by MattBlissett** [comment]
Do IDNs work?

`example@prøve.dk` is a valid address, but I don't know if it gets punycoded to `example@xn--prve-hra.dk` (the real domain) before the API sees it.

(Or `अजय@डाटा.भारत`)

**Comment by cgendreau** [comment]
IDNs will only be accepted if converted to Punycode first (wish is not the case at the moment). If at some point it is needed, the regex can be updated to use `\p{L}\p{M}` instead of `A-Za-z`.
