### ISSUE TITLE
Publisher param in map API appears not to work

### ISSUE THREAD

**Issue by dshorthouse** [gbif/gbif-api#26]
Use of the publisher param as is documented appears to be ignored in the map API. Example: https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?publisher=a41250f0-7c3e-11d8-a19c-b8a03c50a862&style=purpleYellow.point vs https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?style=purpleYellow.point

**Comment by MortenHofft** [comment]
https://api.gbif.org/v2/map/occurrence/density/0/0/0@1x.png?publishingOrg=a41250f0-7c3e-11d8-a19c-b8a03c50a862&style=purpleYellow.point should do it

`publishingOrg`

**Comment by MortenHofft** [comment]
I'll go through the documentation to update it
