### ISSUE TITLE
Any place where api's response structures are explanained?

### ISSUE THREAD

**Issue by javierseixas** [gbif/gbif-api#41]
Hello!

I'm looking for GBIF API's responses documentation. If this is not the place to ask, please, address me to the correct one.

I'm currently working with the GBIF API, and I don't understand some of the responses. For example, when asking for dataset metrics `GET /v1/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c/metrics` I get that response:
```json
{
    "key": 210029,
    "datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
    "usagesCount": 5858142,
    "synonymsCount": 2361744,
    "distinctNamesCount": 5844412,
    "nubMatchingCount": 3805144,
    "colMatchingCount": 2845782,
    "nubCoveragePct": 64,
    "colCoveragePct": 48,
    "countByConstituent": ,
    "countByKingdom": {
        "ANIMALIA": 1529953,
        "PLANTAE": 523372,
        "FUNGI": 201853,
        "CHROMISTA": 15357,
        "BACTERIA": 10847,
        "PROTOZOA": 7063,
        "INCERTAE_SEDIS": 787,
        "ARCHAEA": 439,
        "VIRUSES": 119
    },
    ...
}
```

What is the meaning of properties such as `nubMatchingCount`, `colMatchingCount`, `nubCoveragePct`, etc?? In the website I can see the API documentation for making request, not explaining responses though.

I will appreciate any help Thanks!

**Comment by mdoering** [comment]
Hi Javier,

you are right, we are lacking a documentation on our API models on our site.
The best and probably only place you can find something to read is the java documentation which is here:
https://github.com/gbif/gbif-api/tree/master/src/main/java/org/gbif/api/model

For example the checklist dataset metrics you have mentioned is this:
https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/model/checklistbank/DatasetMetrics.java#L40

... but it lacks documentation for the properties you were mentioning.

"nub" is an alias for "backbone" in GBIF. Hence nubMatchingCount is the count of name usages that can be matched to the GBIF backbone, i.e. do have a corresponding name in the backbone. Similar colMatchingCount is the number of usages that can be matched to the Catalogue of Life. The xxxCoveragePct properties are the same just expressed as percentages compared to the total of the dataset.

Hope that helps a little.
If you have any further questions please use our API mailing list which I have copied in here to get help.

Regards,
Markus

**Comment by javierseixas** [comment]
Thank you very much, Markus, for your quick response, and for your explanations. It helped.

I already subscribedto the API mailing list, which I found [here](https://lists.gbif.org/mailman/listinfo/api-users).

Regards,
Javier
