### ISSUE TITLE
Define GBIF Region for each country

### ISSUE THREAD

**Issue by cgendreau** [gbif/gbif-api#6]
In the [Country](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/Country.java) enumeration, we should be able to declare the associated [GbifRegion](https://github.com/gbif/gbif-api/blob/master/src/main/java/org/gbif/api/vocabulary/GbifRegion.java).

**Comment by mdoering** [comment]
is a country always part of one region only? E.g. Russia, Turkey?

**Comment by cgendreau** [comment]
I would say yes, always part of only one region. The main purpose, as today, of this addition is to generate reports by region. But I would like to have a confirmation from @kcopas .

**Comment by MattBlissett** [comment]
This will quickly get complicated.

The Country enumeration isn't countries, it's ISO countries, territories and islands.  The country France is composed of Metropolitain France (FR), plus overseas departments (RE, MQ etc), plus territories (TF etc). They're in different regions.

**Comment by ahahn-gbif** [comment]
There is a difference between "GBIF Region" and geographic region. Participant countries make an active decision which GBIF region they want to belong to, e.g. as participation in regional meetings is concerned. So in that case, there should indeed be exactly one region per country, contrary to the other region concept that we use for data filters. France->Europe, but also Israel->Europe. Whether it makes sense to apply the GBIF region depends on the context.

**Comment by kcopas** [comment]
Here's an updated spreadsheet with ISO-2 and ISO-3 codes crosswalked to IPBES regions and subregions.
[IPBES regions & ISO country codes](https://github.com/gbif/gbif-api/files/708232/ipbes-regions-countries.xlsx)

**Comment by cgendreau** [comment]
What should we do with Antartica (`Excluded` in the IPBES file)?
We don't assign any GBIF Region?

**Comment by dschigel** [comment]
@cgendreau note there is AnatBIF based in Belgium http://ipt.biodiversity.aq/

**Comment by cgendreau** [comment]
We will add GBIFRegion.ANTARCTICA that will represent Antarctica and adjacent islands.

**Comment by cgendreau** [comment]
Fixed by https://github.com/gbif/gbif-api/commit/6a78a86868a4174794e060dab31c30d847b3944f
