### ISSUE TITLE
Change GADM search API

### ISSUE THREAD

**Issue by MattBlissett** [gbif/gbif-api#65]
We've found some limitations with the initial, basic GADM search implementation.

One is an inconvenience.  A query "the island of Ireland" seems very reasonable, but because different query terms are ANDed (and multiple values for the same term are ORd) this is the necessary query — every appropriate Level 1 GID: 

https://api.gbif.org/v1/occurrence/search?gadmLevel1Gid=IRL.1_1&gadmLevel1Gid=IRL.2_1&gadmLevel1Gid=IRL.3_1&gadmLevel1Gid=IRL.4_1&gadmLevel1Gid=IRL.5_1&gadmLevel1Gid=IRL.6_1&gadmLevel1Gid=IRL.7_1&gadmLevel1Gid=IRL.8_1&gadmLevel1Gid=IRL.9_1&gadmLevel1Gid=IRL.10_1&gadmLevel1Gid=IRL.11_1&gadmLevel1Gid=IRL.12_1&gadmLevel1Gid=IRL.13_1&gadmLevel1Gid=IRL.14_1&gadmLevel1Gid=IRL.15_1&gadmLevel1Gid=IRL.16_1&gadmLevel1Gid=IRL.17_1&gadmLevel1Gid=IRL.18_1&gadmLevel1Gid=IRL.19_1&gadmLevel1Gid=IRL.20_1&gadmLevel1Gid=IRL.21_1&gadmLevel1Gid=IRL.22_1&gadmLevel1Gid=IRL.23_1&gadmLevel1Gid=IRL.24_1&gadmLevel1Gid=IRL.25_1&gadmLevel1Gid=IRL.26_1&gadmLevel1Gid=GBR.2_1

A similar case, "Andalucia and Gibraltar", cannot be done:

https://api.gbif.org/v1/occurrence/search?gadmLevel1Gid=ESP.1_1&gadmLevel0Gid=GIB

Gibraltar doesn't have level 1 subdivisions, so there's no way to make a suitable OR-query.

Secondly, allowing queries by name will probably lead to confusion.  Bolívar is the name of 30 level 2 areas, in 6 countries: https://api.gbif.org/v1/occurrence/search?gadmLevel2Name=Bol%C3%ADvar&limit=0&facet=gadmLevel0Name plus additional level 1 and 3 areas.

----

### Proposal: 

1. Just remove the name parameters. Allowing their use is too fragile. We don't accept `country=Ireland` anyway.

2. An additional search parameter `gadmGid`, so the above queries can be represented like this:

https://api.gbif.org/v1/occurrence/search?gadmGid=IRL&gadmGid=GBR.2_1

https://api.gbif.org/v1/occurrence/search?gadmGid=ESP.1_1&gadmGid=GIB

#### Question 1

This still leaves the facets.  Do we still need `gadmLevel1Gid` etc terms to return in facets, or should something else be done?

Working in a similar way to searching taxa would suggest we have both, as we can already facet on both `kingdomKey`, `phylumKey` etc and `taxonKey`.

<details><summary>To help anyone who can ponder this, these are the GADM areas for Ireland + Northern Ireland:</summary>

 gid_0 |  gid_1   |   gid_2    |    gid_3     |     name_0     |      name_1      |             name_2              |      name_3
-------|----------|------------|--------------|----------------|------------------|---------------------------------|------------------
 GBR   | GBR.2_1  | GBR.2.10_1 | GBR.2.10.1_1 | United Kingdom | Northern Ireland | Newry, Mourne and Down          | Down
 GBR   | GBR.2_1  | GBR.2.10_1 | GBR.2.10.2_1 | United Kingdom | Northern Ireland | Newry, Mourne and Down          | Newry and Mourne
 GBR   | GBR.2_1  | GBR.2.11_1 | GBR.2.11.1_1 | United Kingdom | Northern Ireland | North Down and Ards             | Ards
 GBR   | GBR.2_1  | GBR.2.11_1 | GBR.2.11.2_1 | United Kingdom | Northern Ireland | North Down and Ards             | North Down
 GBR   | GBR.2_1  | GBR.2.1_1  | GBR.2.1.1_1  | United Kingdom | Northern Ireland | Antrim and Newtownabbey         | Antrim
 GBR   | GBR.2_1  | GBR.2.1_1  | GBR.2.1.2_1  | United Kingdom | Northern Ireland | Antrim and Newtownabbey         | Newtownabbey
 GBR   | GBR.2_1  | GBR.2.2_1  | GBR.2.2.1_1  | United Kingdom | Northern Ireland | Armagh, Banbridge and Craigavon | Armagh
 GBR   | GBR.2_1  | GBR.2.2_1  | GBR.2.2.2_1  | United Kingdom | Northern Ireland | Armagh, Banbridge and Craigavon | Banbridge
 GBR   | GBR.2_1  | GBR.2.2_1  | GBR.2.2.3_1  | United Kingdom | Northern Ireland | Armagh, Banbridge and Craigavon | Craigavon
 GBR   | GBR.2_1  | GBR.2.3_1  | GBR.2.3.1_1  | United Kingdom | Northern Ireland | Belfast                         | Belfast
 GBR   | GBR.2_1  | GBR.2.4_1  | GBR.2.4.1_1  | United Kingdom | Northern Ireland | Causeway Coast and Glens        | Ballymoney
 GBR   | GBR.2_1  | GBR.2.4_1  | GBR.2.4.2_1  | United Kingdom | Northern Ireland | Causeway Coast and Glens        | Coleraine
 GBR   | GBR.2_1  | GBR.2.4_1  | GBR.2.4.3_1  | United Kingdom | Northern Ireland | Causeway Coast and Glens        | Limavady
 GBR   | GBR.2_1  | GBR.2.4_1  | GBR.2.4.4_1  | United Kingdom | Northern Ireland | Causeway Coast and Glens        | Moyle
 GBR   | GBR.2_1  | GBR.2.5_1  | GBR.2.5.1_1  | United Kingdom | Northern Ireland | Derry and Strabane              | Derry
 GBR   | GBR.2_1  | GBR.2.5_1  | GBR.2.5.2_1  | United Kingdom | Northern Ireland | Derry and Strabane              | Strabane
 GBR   | GBR.2_1  | GBR.2.6_1  | GBR.2.6.1_1  | United Kingdom | Northern Ireland | Fermanagh and Omagh             | Fermanagh
 GBR   | GBR.2_1  | GBR.2.6_1  | GBR.2.6.2_1  | United Kingdom | Northern Ireland | Fermanagh and Omagh             | Omagh
 GBR   | GBR.2_1  | GBR.2.7_1  | GBR.2.7.1_1  | United Kingdom | Northern Ireland | Lisburn and Castlereagh         | Castlereagh
 GBR   | GBR.2_1  | GBR.2.7_1  | GBR.2.7.2_1  | United Kingdom | Northern Ireland | Lisburn and Castlereagh         | Lisburn
 GBR   | GBR.2_1  | GBR.2.8_1  | GBR.2.8.1_1  | United Kingdom | Northern Ireland | Mid and East Antrim             | Ballymena
 GBR   | GBR.2_1  | GBR.2.8_1  | GBR.2.8.2_1  | United Kingdom | Northern Ireland | Mid and East Antrim             | Carrickfergus
 GBR   | GBR.2_1  | GBR.2.8_1  | GBR.2.8.3_1  | United Kingdom | Northern Ireland | Mid and East Antrim             | Larne
 GBR   | GBR.2_1  | GBR.2.9_1  | GBR.2.9.1_1  | United Kingdom | Northern Ireland | Mid Ulster                      | Cookstown
 GBR   | GBR.2_1  | GBR.2.9_1  | GBR.2.9.2_1  | United Kingdom | Northern Ireland | Mid Ulster                      | Dungannon
 GBR   | GBR.2_1  | GBR.2.9_1  | GBR.2.9.3_1  | United Kingdom | Northern Ireland | Mid Ulster                      | Magherafelt
 IRL   | IRL.10_1 | ␀          | ␀            | Ireland        | Kilkenny         | ␀                               | ␀
 IRL   | IRL.11_1 | ␀          | ␀            | Ireland        | Laoighis         | ␀                               | ␀
 IRL   | IRL.12_1 | ␀          | ␀            | Ireland        | Leitrim          | ␀                               | ␀
 IRL   | IRL.13_1 | ␀          | ␀            | Ireland        | Limerick         | ␀                               | ␀
 IRL   | IRL.14_1 | ␀          | ␀            | Ireland        | Longford         | ␀                               | ␀
 IRL   | IRL.15_1 | ␀          | ␀            | Ireland        | Louth            | ␀                               | ␀
 IRL   | IRL.16_1 | ␀          | ␀            | Ireland        | Mayo             | ␀                               | ␀
 IRL   | IRL.17_1 | ␀          | ␀            | Ireland        | Meath            | ␀                               | ␀
 IRL   | IRL.18_1 | ␀          | ␀            | Ireland        | Monaghan         | ␀                               | ␀
 IRL   | IRL.19_1 | ␀          | ␀            | Ireland        | Offaly           | ␀                               | ␀
 IRL   | IRL.1_1  | ␀          | ␀            | Ireland        | Carlow           | ␀                               | ␀
 IRL   | IRL.20_1 | ␀          | ␀            | Ireland        | Roscommon        | ␀                               | ␀
 IRL   | IRL.21_1 | ␀          | ␀            | Ireland        | Sligo            | ␀                               | ␀
 IRL   | IRL.22_1 | ␀          | ␀            | Ireland        | Tipperary        | ␀                               | ␀
 IRL   | IRL.23_1 | ␀          | ␀            | Ireland        | Waterford        | ␀                               | ␀
 IRL   | IRL.24_1 | ␀          | ␀            | Ireland        | Westmeath        | ␀                               | ␀
 IRL   | IRL.25_1 | ␀          | ␀            | Ireland        | Wexford          | ␀                               | ␀
 IRL   | IRL.26_1 | ␀          | ␀            | Ireland        | Wicklow          | ␀                               | ␀
 IRL   | IRL.2_1  | ␀          | ␀            | Ireland        | Cavan            | ␀                               | ␀
 IRL   | IRL.3_1  | ␀          | ␀            | Ireland        | Clare            | ␀                               | ␀
 IRL   | IRL.4_1  | ␀          | ␀            | Ireland        | Cork             | ␀                               | ␀
 IRL   | IRL.5_1  | ␀          | ␀            | Ireland        | Donegal          | ␀                               | ␀
 IRL   | IRL.6_1  | ␀          | ␀            | Ireland        | Dublin           | ␀                               | ␀
 IRL   | IRL.7_1  | ␀          | ␀            | Ireland        | Galway           | ␀                               | ␀
 IRL   | IRL.8_1  | ␀          | ␀            | Ireland        | Kerry            | ␀                               | ␀
 IRL   | IRL.9_1  | ␀          | ␀            | Ireland        | Kildare          | ␀                               | ␀
</details>

#### Question 2

Should there be any special behaviour with the existing `country` parameter?  At the moment, a query like https://api.gbif.org/v2/map/occurrence/adhoc/5/30/6@2x.png?srs=EPSG:4326&bin=hex&hexPerTile=17&style=classic.poly&country=IE&gadmLevel1Gid=GBR.2_1 returns only those occurrences in *both* NaturalEarthMarineRegions Ireland *and* GADM Northern Ireland, i.e. the errors and inaccuracies from the data for occurrences close to the border between the two.

**Comment by MortenHofft** [comment]
> An additional search parameter gadmGid ...

I too had imagined having a catch all GID param like that. The GIDs are unique as far as I know, it seems redundant to specify the level in search. It also has the benefit that I can search for say Denmark and Malmø as they are OR'ed (Similar to above example I believe).

**Comment by MattBlissett** [comment]
> Keeping search by name is useful if we want to do suggests driven of ES for scoped portals.
> It is then possible to do a search by name and facet by gadmGid and use those facets as suggestions. I isn't a high priority for now - but we loose that possibility if we do not include names in the index.

Is that needed? We don't have a facet way to return kingdom names.  We will provide a lookup service from GID→name, and the result can be cached indefinitely.

There are duplicate area names in neighbouring countries, e.g. there's a "Berg" municipality in both Norway and Sweden.

**Comment by MortenHofft** [comment]
No I do not believe names are needed in the occurrence index - not with @fmendezh suggestion for an autocomplete where suggestions can be scoped geographically (only give me suggestions for locations within this GID). If so it would only be for the benefit of unstructured search `?q=Ringsted`

**Comment by MattBlissett** [comment]
This is ready in UAT.
