### ISSUE TITLE
Add ISOPARATYPE into TypeStatus

### ISSUE THREAD

**Issue by qifeng-bai** [gbif/gbif-api#72]
ISOPARATYPE has been used in Atals

**Comment by mdoering** [comment]
It seems indeed to be a valid status:

https://plants.jstor.org/stable/10.5555/al.ap.specimen.ill00009854

https://cybertaxonomy.eu/cdmlib/apidocs/eu/etaxonomy/cdm/model/name/SpecimenTypeDesignationStatus.html#ISOPARATYPE--

http://www.insdc.org/controlled-vocabulary-typematerial-qualifer

**Comment by javier-molina** [comment]
@mdoering I'm following up on this issue from the analysis @qifeng-bai ( Bai) did at our end https://github.com/atlasoflivingaustralia/la-pipelines/issues/56

Could you please clarify whether this commit is the only change need it to address this issue and if it has already been included in a CoL Backend release?

**Comment by mdoering** [comment]
I have added it to COL already, which also required a database type change:
https://github.com/CatalogueOfLife/backend/commit/717a4f23fa7508d4552818bf5cafd1f75b600c8e

As for the GBIF API change this only impacts the Occurrence store as we do not store type specimens for checklists, only type species and genera. All specimens are dealt with as regular occurrences. @fmendezh @timrobertson100 @mike-podolskiy90 does this patch need anything more than the pure enumeration change?

**Comment by javier-molina** [comment]
Bump! See last two comments

@timrobertson100, @mike-podolskiy90

**Comment by timrobertson100** [comment]
Thanks for the reminder @javier-molina 
This is underway

**Comment by MattBlissett** [comment]
This is done, GBIF API version 0.135.
