### ISSUE TITLE
Enumeration for literature topics

### ISSUE THREAD

**Issue by nickynicolson** [gbif/gbif-api#74]
Is there an enumeration available through the REST API which contains the topics applied to literature monitored by the GBIF DOI tracking programme? View source on the web UI (https://www.gbif.org/resource/search?contentType=literature) shows a reference to `enums.cms.vocabularyTerms.topics` but I can't see this listed under https://gbif.github.io/gbif-api/apidocs/org/gbif/api/vocabulary/package-summary.html - I assume only those listed here are available through the API access to enumerations: https://www.gbif.org/developer/summary#enumerations

**Comment by mike-podolskiy90** [comment]
http://api.gbif.org/v1/enumeration/basic/LiteratureRelevance
http://api.gbif.org/v1/enumeration/basic/LiteratureType
http://api.gbif.org/v1/enumeration/basic/LiteratureTopic
