### ISSUE TITLE
language codes for vernacular names appear to be capitalized (was: "eng" currently: "ENGLISH")

### ISSUE THREAD

**Issue by jhpoelen** [gbif/gbif-api#95]
Previously, 

http://api.gbif.org/v1/species/2882753/vernacularNames

would return ISO 639-3 compatible language codes like "eng",
however,
as of today 2022-09-12,  it appears that the language codes are all-caps (e.g., "ENGLISH"). These all-cap language names appear not to be ISO 639 compatible (see https://iso639-3.sil.org/code_tables/639/data/e and attached screenshot).

Suggest to revert language codes of vernacular names to ISO 639 compatible strings. 

![Screenshot from 2022-09-12 14-31-34](https://user-images.githubusercontent.com/1084872/189740034-29625e45-5496-4391-bb3d-4e8454152c08.png)

**Comment by mdoering** [comment]
Looks like the enum is serialized directly, not using the ISO serializer.

**Comment by marcos-lg** [comment]
Fixed

**Comment by jhpoelen** [comment]
@marcos-lg @mdoering Thanks for your prompt reply!

I reverted my workaround, and the integration tests passed as before.
